import type { DashboardStats, MailEmail } from '@/types'

export const demoUser = {
  mode: 'demo' as const,
  email: 'jordan@mailos.dev',
  name: 'Jordan Davis',
}

export const demoStats: DashboardStats = {
  unread: 247,
  recruiters: 6,
  interviews: 2,
  invoices: '₹12,000',
  followUps: 9,
}

export const demoEmails: MailEmail[] = [
  {
    id: 'em_google_interview',
    subject: 'Interview Invitation — Software Engineer',
    sender: 'Sarah Chen',
    senderEmail: 'sarah.chen@google.com',
    snippet: 'Can you join tomorrow at 3 PM for a technical conversation?',
    body: 'Hi Jordan,\n\nWe were impressed by your resume. Can you join tomorrow at 3 PM for a Software Engineer interview?\n\nBest,\nSarah Chen\nGoogle Recruiting',
    receivedAt: '2026-09-24T10:42:00.000Z',
    unread: true,
    jev: { category: 'INTERVIEW', priority: 'HIGH', needs_reply: true, calendar: true, confidence: 0.99 },
    groq: { company: 'Google', date: 'Tomorrow', time: '3 PM', amount: null, actions: ['Reply', 'Set Reminder'] },
  },
  {
    id: 'em_aws_invoice',
    subject: 'Your AWS invoice is ready',
    sender: 'AWS Billing',
    senderEmail: 'no-reply@amazon.com',
    snippet: 'Invoice INV-2048 for ₹12,000 is due tomorrow.',
    body: 'Your Amazon Web Services invoice INV-2048 for ₹12,000 is ready. Payment is due tomorrow to avoid service interruption.',
    receivedAt: '2026-09-24T09:18:00.000Z',
    unread: true,
    jev: { category: 'INVOICE', priority: 'HIGH', needs_reply: false, calendar: false, confidence: 0.97 },
    groq: { company: 'AWS', date: 'Tomorrow', time: null, amount: '₹12,000', actions: ['Pay Invoice', 'Add Reminder'] },
  },
  {
    id: 'em_amazon_recruiter',
    subject: 'Following up on your application',
    sender: 'Priya Nair',
    senderEmail: 'priya.nair@amazon.com',
    snippet: 'Just checking in — are you still interested in the SDE role?',
    body: 'Hi Jordan, following up on your Software Development Engineer application. Are you free for a quick call this week?\n\nPriya Nair\nAmazon University Recruiting',
    receivedAt: '2026-09-23T16:05:00.000Z',
    unread: true,
    jev: { category: 'RECRUITER', priority: 'HIGH', needs_reply: true, calendar: false, confidence: 0.96 },
    groq: { company: 'Amazon', date: 'This week', time: null, amount: null, actions: ['Reply', 'Follow up'] },
  },
  {
    id: 'em_meta_recruiter',
    subject: 'Intro from Meta University Recruiting',
    sender: 'Alex Rivera',
    senderEmail: 'arivera@meta.com',
    snippet: 'Would love to share a few roles on the Infra team.',
    body: 'Hi Jordan — I lead new grad recruiting for Meta Infra. Would love 20 minutes to walk through open roles.',
    receivedAt: '2026-09-23T14:22:00.000Z',
    unread: true,
    jev: { category: 'RECRUITER', priority: 'MEDIUM', needs_reply: true, calendar: false, confidence: 0.94 },
    groq: { company: 'Meta', date: null, time: null, amount: null, actions: ['Reply'] },
  },
  {
    id: 'em_stripe_interview',
    subject: 'Stripe — onsite loop confirmation',
    sender: 'Campus Recruiting',
    senderEmail: 'university@stripe.com',
    snippet: 'Your onsite is confirmed for Friday 11 AM.',
    body: 'Your Stripe intern onsite loop is confirmed for Friday at 11 AM. Please reply if you need to reschedule.',
    receivedAt: '2026-09-23T11:40:00.000Z',
    unread: true,
    jev: { category: 'INTERVIEW', priority: 'HIGH', needs_reply: true, calendar: true, confidence: 0.98 },
    groq: { company: 'Stripe', date: 'Friday', time: '11 AM', amount: null, actions: ['Reply', 'Set Reminder'] },
  },
  {
    id: 'em_linear_followup',
    subject: 'Re: Product design exercise',
    sender: 'Maya Patel',
    senderEmail: 'maya@linear.app',
    snippet: 'Just checking in on this — happy to answer any questions.',
    body: 'Hey, following up on the take-home. No rush, but we’d love an update when you can.',
    receivedAt: '2026-09-22T18:12:00.000Z',
    unread: true,
    jev: { category: 'FOLLOW_UP', priority: 'MEDIUM', needs_reply: true, calendar: false, confidence: 0.91 },
    groq: { company: 'Linear', date: null, time: null, amount: null, actions: ['Reply', 'Follow up'] },
  },
  {
    id: 'em_notion_followup',
    subject: 'Did you get a chance to review?',
    sender: 'Chris Wong',
    senderEmail: 'chris@notion.so',
    snippet: 'Circling back on the internship offer timeline.',
    body: 'Circling back — we need a decision by Monday so we can close the intern class.',
    receivedAt: '2026-09-22T09:04:00.000Z',
    unread: true,
    jev: { category: 'FOLLOW_UP', priority: 'HIGH', needs_reply: true, calendar: false, confidence: 0.93 },
    groq: { company: 'Notion', date: 'Monday', time: null, amount: null, actions: ['Reply'] },
  },
  {
    id: 'em_figma_recruiter',
    subject: 'Figma early career — designer x engineer',
    sender: 'Leah Kim',
    senderEmail: 'leah.kim@figma.com',
    snippet: 'Saw your MailOS prototype. Want to talk?',
    body: 'Your inbox-OS framing is exactly the kind of product thinking we look for. Open to a chat this week?',
    receivedAt: '2026-09-21T20:15:00.000Z',
    unread: true,
    jev: { category: 'RECRUITER', priority: 'MEDIUM', needs_reply: true, calendar: false, confidence: 0.92 },
    groq: { company: 'Figma', date: 'This week', time: null, amount: null, actions: ['Reply'] },
  },
  {
    id: 'em_vercel_invoice',
    subject: 'Vercel Pro invoice — September',
    sender: 'Vercel Billing',
    senderEmail: 'billing@vercel.com',
    snippet: '$20.00 charged to your card ending 4242.',
    body: 'Your Vercel Pro invoice for September is $20.00. No action needed unless you want to update the card.',
    receivedAt: '2026-09-21T08:00:00.000Z',
    unread: false,
    jev: { category: 'INVOICE', priority: 'LOW', needs_reply: false, calendar: false, confidence: 0.95 },
    groq: { company: 'Vercel', date: 'September', time: null, amount: '$20', actions: ['Mark Done'] },
  },
  {
    id: 'em_spam_crypto',
    subject: 'URGENT: claim 3.2 BTC now',
    sender: 'Wallet Support',
    senderEmail: 'payouts@secure-wallets.biz',
    snippet: 'Your wallet will be frozen unless you verify.',
    body: 'Click here to claim 3.2 BTC. This is not affiliated with any exchange you use.',
    receivedAt: '2026-09-21T07:44:00.000Z',
    unread: true,
    jev: { category: 'SPAM', priority: 'LOW', needs_reply: false, calendar: false, confidence: 0.99 },
    groq: { company: 'Unknown', date: null, time: null, amount: null, actions: ['Mark Done'] },
  },
  {
    id: 'em_newsletter',
    subject: 'This week in AI agents',
    sender: 'Latent Space',
    senderEmail: 'hi@latent.space',
    snippet: 'Jev vs Groq — splitting classification from extraction.',
    body: 'A roundup of agent architectures. Worth a skim, not a reply.',
    receivedAt: '2026-09-20T15:30:00.000Z',
    unread: false,
    jev: { category: 'OTHER', priority: 'LOW', needs_reply: false, calendar: false, confidence: 0.88 },
    groq: { company: 'Latent Space', date: null, time: null, amount: null, actions: [] },
  },
  {
    id: 'em_microsoft_recruiter',
    subject: 'Microsoft Explore — next steps',
    sender: 'Devon Blake',
    senderEmail: 'devon.blake@microsoft.com',
    snippet: 'Can you send availability for a 30-min screen?',
    body: 'Hi Jordan, we’d like to move forward. Send 3 slots this week for a recruiter screen.',
    receivedAt: '2026-09-20T13:11:00.000Z',
    unread: true,
    jev: { category: 'RECRUITER', priority: 'HIGH', needs_reply: true, calendar: true, confidence: 0.95 },
    groq: { company: 'Microsoft', date: 'This week', time: '30 min', amount: null, actions: ['Reply', 'Set Reminder'] },
  },
]
